CREATE TABLE COUNTRY (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO COUNTRY (id, name) VALUES (1, 'USA');
INSERT INTO COUNTRY (id, name) VALUES (2, 'France');
INSERT INTO COUNTRY (id, name) VALUES (3, 'Brazil');
INSERT INTO COUNTRY (id, name) VALUES (4, 'Italy');
INSERT INTO COUNTRY (id, name) VALUES (5, 'Canada');
